#!/bin/tcsh -e
#SBATCH --job-name=Synaptic-inference # Job name
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task 48 # 1 cpu on single node
#SBATCH --mem=248gb # Job memory request
#SBATCH --time=120:00:00 # Time limit hrs:min:sec
#SBATCH --mail-type=BEGIN,END,FAIL. # Mail events (NONE, BEGIN, END, FAIL, ALL)
#SBATCH --mail-user=guptanp@bc.edu  # Where to send mmail
#SBATCH --partition=gpua100

#SBATCH --output=main_%j.out

module purge
module load anaconda
module load slurm
module load cuda11.2/blas/11.2.2

conda activate py3_torch

which python
hostname
python -c 'import torch; print(torch.version.cuda)'

cd /mmfs1/data/guptani/pytorch_connectomics
setenv PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION python
setenv CUDA_VISIBLE_DEVICES 0

python -u scripts/main.py --inference \
 --config-base configs/JWR15/synapse/JWR15-Synapse-Base.yaml \
 --config-file configs/JWR15/synapse/JWR15-Synapse-BCE.yaml \
 --checkpoint outputs/nagP7/fine-tuned_Semantic-CE/checkpoint_165000.pth.tar


